# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  cats-blender-plugin-unofficial = {
    pname = "cats-blender-plugin-unofficial";
    version = "f7f6962c41e342202729dd2020586bf5a27dde4d";
    src = fetchgit {
      url = "https://git.disroot.org/Neoneko/Cats-Blender-Plugin.git";
      rev = "f7f6962c41e342202729dd2020586bf5a27dde4d";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-a6WBgPgjXZXgZqfCIuk1xlzdDbkbj+W40cAMXEgAFrI=";
    };
    date = "2026-01-24";
  };
  disblock-origin = {
    pname = "disblock-origin";
    version = "15cbab89197af9f4af6b404ad0c5ea922cc9c380";
    src = fetchgit {
      url = "https://git.allpurposem.at/mat/Disblock-Origin.git";
      rev = "15cbab89197af9f4af6b404ad0c5ea922cc9c380";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-mIDj3gf4I1f+u/jzqeNiIqLaR173bkxO9Nq0PBXhws8=";
    };
    date = "2026-01-14";
  };
  osc-goes-brrr = {
    pname = "osc-goes-brrr";
    version = "6a3421f0a755e990238b2d75b71b66430f029929";
    src = fetchgit {
      url = "https://github.com/OscToys/OscGoesBrrr.git";
      rev = "6a3421f0a755e990238b2d75b71b66430f029929";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-JC86IHzntcgqdAcGAUotX7iwj3iIQwC2j2O3+QA77Tw=";
    };
    date = "2025-11-17";
  };
}
